<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BeStrategy.Infrastructure</RootNamespace>
    <AssemblyName>BeStrategy.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BeStrategy.Application\BeStrategy.Application.csproj" />
    <ProjectReference Include="..\BeStrategy.Domain\BeStrategy.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>

</Project>
